/* empty css                     */import{a as u}from"./assets/vendor-1b0a9daf.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const d=document.querySelector(".render-btn-list-pagination"),p=(t,n)=>{let i="";for(let o=1;o<=t;o++){let e=` <li>
        <button
          class="render-pagination-btn "
          type="button"
        >${o}</button></li>`;i+=e}d.innerHTML=i,d.children[n-1].children[0].classList.add("render-pagination-btn-active")},g=u.create({baseURL:"https://energyflow.b.goit.study/api/"}),m=async t=>{try{return await g.get("filters",{params:t})}catch(n){console.log(n)}},f={getFilters:m},c=async t=>{const n={...t},i=await f.getFilters(n),o=i.data.results;return p(i.data.totalPages,t.page),o.reduce((r,a)=>r+` <li class="render-page-one-item" data-name="${a.name}">
            <img src="${a.imgUrl}" alt="" />
            <div class="render-page-one-img-container">
              <p class="render-page-one-item-title">${a.name}</p>
              <p class="render-page-one-item-zones">${a.filter}</p>
            </div>
          </li>`,"")},y=document.querySelector(".render-page-one-list"),l=async t=>{const n=await t;y.innerHTML=n},b=document.querySelector(".render-btn-list-pagination");document.querySelector(".render-pagination-btn-active");document.querySelectorAll(".render-pagination-btn");const L=document.querySelector(".render-page-one-list-btn"),h=document.querySelectorAll(".render-page-one-btn"),v=getComputedStyle(document.querySelector("body")).width,S=parseInt(v)<768?8:12,s={limit:S,page:1},q=t=>{t.target.nodeName==="BUTTON"&&(h.forEach(n=>n.classList.remove("render-page-one-btn-active")),t.target.classList.add("render-page-one-btn-active"),s.filter=t.target.textContent.trimStart().trimEnd(),s.page=1,l(c(s)))},E=t=>{s.page=parseInt(t.target.textContent),l(c(s))};b.addEventListener("click",E);L.addEventListener("click",q);l(c({page:1}));
//# sourceMappingURL=commonHelpers2.js.map
