/* empty css                     */import{a as p}from"./assets/vendor-1b0a9daf.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerpolicy&&(n.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?n.credentials="include":e.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(e){if(e.ep)return;e.ep=!0;const n=s(e);fetch(e.href,n)}})();const d=document.querySelector(".render-btn-list-pagination"),g=(t,r)=>{let s="";for(let o=1;o<=t;o++){let e=` <li>
        <button
          class="render-pagination-btn "
          type="button"
        >${o}</button></li>`;s+=e}d.innerHTML=s,d.children[r-1].children[0].classList.add("render-pagination-btn-active")},u=p.create({baseURL:"https://energyflow.b.goit.study/api/"}),m=async t=>{try{return await u.get("filters",{params:t})}catch(r){console.log(r)}},f=async t=>{try{return await u.get("exercises",{params:t})}catch(r){console.log(r)}},y={getFilters:m,getWorkout:f},c=async t=>{const r={...t},s=await y.getFilters(r),o=s.data.results;return g(s.data.totalPages,t.page),o.reduce((n,a)=>n+` <li class="render-page-one-item" data-name="${a.name}">
            <img src="${a.imgUrl}" alt="" />
            <div class="render-page-one-img-container">
              <p class="render-page-one-item-title">${a.name}</p>
              <p class="render-page-one-item-zones">${a.filter}</p>
            </div>
          </li>`,"")},b=document.querySelector(".render-page-one-list"),l=async t=>{const r=await t;b.innerHTML=r},L=document.querySelector(".render-btn-list-pagination");document.querySelector(".render-pagination-btn-active");document.querySelectorAll(".render-pagination-btn");const h=document.querySelector(".render-page-one-list-btn"),v=document.querySelectorAll(".render-page-one-btn"),S=getComputedStyle(document.querySelector("body")).width,q=parseInt(S)<768?8:12,i={limit:q,page:1,filter:"Muscles"},k=t=>{t.target.nodeName==="BUTTON"&&(v.forEach(r=>r.classList.remove("render-page-one-btn-active")),t.target.classList.add("render-page-one-btn-active"),i.filter=t.target.textContent.trimStart().trimEnd(),i.page=1,l(c(i)))},E=t=>{i.page=parseInt(t.target.textContent),l(c(i))};L.addEventListener("click",E);h.addEventListener("click",k);l(c({page:1,filter:"Muscles"}));
//# sourceMappingURL=commonHelpers2.js.map
